### ISSUE TITLE
API thoughts

### ISSUE THREAD

**Issue by joto** [mapbox/pbf.hpp#11]
Because the API of `pbf.hpp` is very low-level it is really easy to shoot yourself in the foot using it. What can we do to make it more robust and easier to use? I think it makes sense to think about this a little bit before we port all the software using it to the new version.

Here are some random ideas/comments:

* `varint()`, `svarint()`, and `fixed()` are templated functions. They use a default of `uint32_t`, maybe it would be better to not have a default so users will have to be explicit and there is less chance of accidental wrong casting? Or we could remove the templates (or change them to be private) and have functions like `varint_int64()` or whatever. There are functions `std::float32()` and `std::float64()` already which basically do just this.
* If we keep templates, they should probably check their argument: `std::is_integral<T>` etc.
* We can sprinkle some `noexcept` around and maybe some `constexpr`.
* The `pbf::string()` functions has the overhead of allocating a `std::string`. It is the only function that needs the heap. We can add a lower-level function `pbf::data()` or so that gives back a `std::pair<const char*, size_t>` or similar. Maybe a `pbf::string(std::string& str)` that copies the data to an existing string?
* There is currently no special support for *packed repeated fields*. Do we need that?
* How do we handle the case when a `varint` is larger that the type we give it to?
* The current code can only handle 32 bit strings and embedded messages. Is that intended? (I know it is unlikely that we want strings or embedded messages that large...)
* We can probably make `pbf` a POD/trivial type. Could allow some more compiler optimizations.

/cc @artemp @kkaefer @springmeyer

**Comment by springmeyer** [comment]
- In terms of templated functions for ints: I'm supportive of removing the default at the least.
- I like the idea of all the functions consistently not using the heap. Returning `std::pair<const char*, size_t>` sounds good (c++11 does not yet have an official `string_ref` implementation, right?)
- `packed` repeated fields are common (e.g. the geometry array in vector tiles) - better support would be welcome
- :+1:  to `noexept` and `constexpr` and other c++11 best practices

**Comment by joto** [comment]
These issue have now all been adressed in the current code.
