### ISSUE TITLE
Provide accessor functions with checks?

### ISSUE THREAD

**Issue by joto** [mapbox/pbf.hpp#12]
Currently the functions to access the pbf encoded data don't check whether it has the right format. Should we add functions that do?

    auto a = pbf.varint(); // what if it is not a varint?
    auto a = pbf.checked_varint(); // throws if it is not

Or should all functions check? This would add some overhead but make everything more robust.

We can add `assert()`s, but this will not solve the problem of intentionally or unintentionally corrupted data in production systems.

/cc @springmeyer @artemp @kkaefer

**Comment by springmeyer** [comment]
My proposal: `pbf.varint()` should check, and `pbf.unchecked_varint()` would not.

What does libprotobuf and https://github.com/haberman/upb do?

**Comment by joto** [comment]
From a short experiment it looks like Google libprotobuf does an assert().

**Comment by springmeyer** [comment]
:+1: to `assert` in debug mode (so `-DNDEBUG`).

**Comment by joto** [comment]
As per voice discussion we'll use `assert()` in the code. I have already implemented that in the current code base. We can later benchmark the code and see whether enabling the checks makes the code significantly slower.
