### ISSUE TITLE
sudo:false for travis builds

### ISSUE THREAD

**Issue by springmeyer** [mapbox/pbf.hpp#16]
Should be easy to get pbf.hpp running on sudo:false travis machines. Looks like the only thing requiring sudo is the `pip install cpp-coveralls`. This can be done without sudo and locally like https://github.com/Project-OSRM/osrm-backend/blob/masonize/scripts/configure_osrm.sh#L12-L20.

**Comment by joto** [comment]
Fixed in 896e38d.
