### ISSUE TITLE
Support for Maps?

### ISSUE THREAD

**Issue by joto** [mapbox/pbf.hpp#17]
Protobuf language guide describes maps: https://developers.google.com/protocol-buffers/docs/prot . But the encoding documentation at https://developers.google.com/protocol-buffers/docs/encoding doesn tell us how they are encoded.

Do we need to support them?

**Comment by mourner** [comment]
@joto no, I don't think so. Maps are equivalent to repeated embedded key/value messages, see https://developers.google.com/protocol-buffers/docs/proto3#maps
