### ISSUE TITLE
Add a writer as well

### ISSUE THREAD

**Issue by mourner** [mapbox/pbf.hpp#2]
mapbox/pbf is both reader and writer, while pbf.hpp is just reader. I think the repo eventually needs a writer too.

**Comment by joto** [comment]
I have added some writing support. There are some things to do before this is final:

* [ ] Write tests that read data written by our library with the official library from Google
* [ ] Improve interface for embedded messages/strings/bytes. Currently they need an extra memory allocation.

**Comment by joto** [comment]
How shall we organize the source code for writing support?

* Everything in one `pbf.hpp` file? (-> easier integration)
* Split up reader and writer into separate files? (This would probably mean one additional file for common stuff) (->users have minimal include)

Opinions?

**Comment by springmeyer** [comment]
@joto I'm fine with either, but splitting feels like the best approach.

**Comment by joto** [comment]
Okay, I have split it up into `pbf_reader.hpp` and `pbf_writer.hpp`, both using `pbf_common.hpp`.

**Comment by mourner** [comment]
Done! Lets open remaining things as separate issues if necessary.
